[build]
  command = "npm run optimize:images"
  publish = "."

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/wp-content/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
