[build]
  command = "npm run optimize:images"
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "CONTACT_AUTOREPLY_FROM,CONTACT_REPLY_TO"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/wp-content/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
